sudo: false
language: go
install: go get -v github.com/netlify/binrc
# before_install:
# - sudo apt-get update
# - sudo apt-get install nodejs
# - sudo apt-get install npm
# before_script:
# - npm install -g gulp
# - npm install
script:
  - binrc install spf13/hugo 0.20.7
  - hugo
  - hugo version
  # - gulp min-html
